# Generated by Django 5.2.6 on 2025-09-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('car_name', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('manufacture_date', models.DateField()),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('insurance_expiry', models.DateField()),
            ],
        ),
    ]
